### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by debnet**
* Fixing displayed URL by using pattern instead of name_parent regex (for namespaced URLs mainly)
* Distinction between custom API views and RESTFul APIs generated through models and routers
* Adding possibility to use app_name in URL patterns for API organisation
* Adding an URL to filter APIs by app_name or name_parent

### CODE REVIEW

**Comment by debnet** [comment]
Tests added for the new features

**Comment by ekonstantinidis** [comment]
A few small bits:
- When in `/docs/app_name/` can we hide the "**Jump to**" dropdown from the navbar?
- Link each app name(heading) to that url? (Maybe on hover show an `#` that links to that url - or something similar)
- What if there is no defined `app_name` for a namespace? Would be great if we can use something like the `parent` so that it works with all the namespaces.

Other than that it looks great! Can't wait to merge it :sparkles:

**Comment by debnet** [comment]
OK, we are working on it. ;)

**Comment by debnet** [comment]
Done. Just to do some styling on title hyperlinks, we leave it to you. ;)

Exemple:

```less
h1 {
   > a {
       color:#2C3E50 ;
       &:hover{
           text-decoration: none;
       }
   }
}
```

**Comment by ekonstantinidis** [comment]
Thank you @debnet! Moving this one to #48. :tada:

**Pull request closed without merging**
