### PR TITLE
Possible fix for #144.

### PR DESCRIPTION
**Pull request by StyXman**
This PR proposes a fix for #144. It WorksForMe™, but I don't know all the internals of DRFDocs. I just hope this makes the ball start rolling.

### CODE REVIEW

**Comment by tadgh** [comment]
Tested this locally, solves it for me as well

**Comment by manosim** [comment]
Hello @StyXman! I'm sorry for the late reply - been really busy - trying to find more time for drfdocs & other open-source projects but it can be really tough. I will be more than happy to give you push access to the repository & pypi so that I don't slow down everyone (sorry about this!)... Let me know if you are interested!

**Comment by StyXman** [comment]
@manosim: yes, I can at least merge a couple of PRs, and if you're happy with it, think about a release. With a little bit of luck I can do it in work hours :)

**Comment by manosim** [comment]
@StyXman Sounds great! Can you send me a dm on twitter ([@manosim_](https://twitter.com/manosim_)) to give me your pypi username etc?

**Comment by StyXman** [comment]
My pypi username is the same as my github one, what else do you need?

**Comment by manosim** [comment]
Just added you to PyPI as well so that should be good to go? Let me know if there is anything else I can help with! Thank you for stepping up on this one! Really appreciate it!

**Comment by ConorMcGee** [comment]
Any idea when this will be released?

**Pull request merged**
