### PR TITLE
Nested serializers support

### PR DESCRIPTION
**Pull request by Ivaylo-Bachvarov**
Take a look at this. 

We added:
- An example for nested serializers in the demo app.
- Support for nested serializer in nested serializer (recursive)
- User friendly interface for the nested serializer data.

Things that we are going to add in a separate pull request:
- Support for Nested Serialization in Live API Endpoints.

Authors: Me and @Ivo-Donchev :panda_face: :beers:

### CODE REVIEW

**Comment by kdkocev** [comment]
:+1:

**Comment by Ivo-Donchev** [comment]
:+1:

**Comment by Rositsazz** [comment]
:+1:

**Comment by ekonstantinidis** [comment]
Hello everyone! Thank you for the PR -looks really good! Can you bring it up to date with master so that we can merge it?

**Comment by Ivaylo-Bachvarov** [comment]
@ekonstantinidis 

Today I will bring it up to date and I will bing you here for a merge.

We are preparing some more PR for that great project :beers:

**Comment by Ivaylo-Bachvarov** [comment]
@ekonstantinidis The PR is up to date with master now :)

**Comment by ekonstantinidis** [comment]
Awesome! It would be great if you can add some tests for this PR at some point?

**Comment by Ivaylo-Bachvarov** [comment]
@ekonstantinidis Upcoming commits with tests and Live API support in this pull request ;)
@Ivo-Donchev will commit soon :beers:

**Comment by Ivaylo-Bachvarov** [comment]
@ekonstantinidis I think that we are done with this. 

We added support for many=True in nested serializing. 

This PR is ready for merge. 
Another PR is comming with Live API Support.

**Comment by ekonstantinidis** [comment]
Hello @Ivaylo-Bachvarov! Sorry for the late reply - been really busy. That looks great so let's merge it!

**Pull request merged**
