### PR TITLE
Added `help_text` to fields

### PR DESCRIPTION
**Pull request by alej0varas**
Show the `help_text` for each field in the documentation

### CODE REVIEW

**Comment by Ivaylo-Bachvarov** [comment]
:+1: This looks nice!

**Comment by ekonstantinidis** [comment]
Hey @alej0varas! Thank you for the PRs! Can you bring this one up to date with master?

**Comment by ekonstantinidis** [comment]
By the way @Ivaylo-Bachvarov, I couldn't find your email so.. let me know if you would like push access to the repo! Been really busy lately and still haven't pushed a new version to pypi with your previous PR.

**Comment by ckcollab** [comment]
@manosim Do you think @alej0varas (maybe myself?) and @Ivaylo-Bachvarov could get access to get some momentum going here? I love this project! :)

**Pull request closed without merging**
