### PR TITLE
Support for ModelViewSet

### PR DESCRIPTION
**Pull request by manosim**
### Work In Progress

> Any help for this one would be much appreciated.

### CODE REVIEW

**Comment by dimitri-justeau** [comment]
I suggest a solution here: [Better support for ModelViewSet (through appropriate router attribution based on settings)](https://github.com/ekonstantinidis/django-rest-framework-docs/pull/132)

**Comment by StyXman** [comment]
@manosim I have a fix for this PR, how can I provide it to you?

**Comment by Pear0** [comment]
When is this fix expected to be published to pypi?

**Comment by StyXman** [comment]
@manosim gave me some power in this repo, he hasn't has time as of late last year. Now I'm not in the job I had and time has run low. Finally, after django-rest got its own self-documenting feature, I don't know how much sense this project makes. 

I think I could try to make a release, but then someone should step up to keep it up. Sorry for the inconvenience :(

**Pull request merged**
