### PR TITLE
removing http:// hardcode on google fonts

### PR DESCRIPTION
**Pull request by cyriac**

### CODE REVIEW

**Comment by christophervalles** [comment]
+1

**Comment by ekonstantinidis** [comment]
Sorry for the late reply @cyriac! Can you merge master into this branch? Will be happy to merge it and release :)

**Comment by cyriac** [comment]
@ekonstantinidis done!

**Comment by ekonstantinidis** [comment]
Thank you @cyriac! 👍 

Release 0.0.11: https://github.com/ekonstantinidis/django-rest-framework-docs/releases/tag/0.0.11
PyPI: https://pypi.python.org/pypi/drfdocs/0.0.11

**Pull request merged**
