### PR TITLE
add viewset support

### PR DESCRIPTION
**Pull request by sebdiem**
This is how I would solve issue https://github.com/ekonstantinidis/django-rest-framework-docs/issues/58.
I think that using the rest framework router, which provides all the magic, is probably the cleanest way.

### CODE REVIEW

**Comment by ekonstantinidis** [comment]
Looks good to me! If someone else can review too that would be great! We can then merge and release to PyPI!

**Comment by preston-scibek** [comment]
Might I suggest adding to the documentation something about adding the following the urls.py if using viewsets and router?
`url(r'^docs/', DRFDocsView.as_view(drf_router=router), name='drfdocs')`

**Comment by egamonal** [comment]
@preston-scibek are you sure?

I added that line with the corresponding import `from rest_framework_docs.views import DRFDocsView
` and I got an error:

> TypeError: DRFDocsView() received an invalid keyword 'drf_router'. as_view only accepts arguments that are already attributes of the class.

**Comment by preston-scibek** [comment]
maybe it is just a bug on my local machine then, I had to do that to get it to work but if it's giving you an error, than it's most likely to do with my machine.

**Pull request merged**
