### PR TITLE
Use get_serializer_class for Views without serlaizer_class attribute

### PR DESCRIPTION
**Pull request by EmadMokhtar**
Sometimes View won't has serliazer_class as [DRF documentations](http://www.django-rest-framework.org/api-guide/generic-views/#genericapiview), so it's nice to get the serializer class using get_serlizer_class if there is no serliazer_class

### CODE REVIEW

**Comment by Ivaylo-Bachvarov** [comment]
:+1:

**Comment by EmadMokhtar** [comment]
@ekonstantinidis The issue from CI regarding the npm error

**Comment by ekonstantinidis** [comment]
That's great @EmadMokhtar! Had to restart Travis several times because it kept erroring (node version?). Will fix that in another PR. Thank you for contributing!

**Comment by ekonstantinidis** [comment]
@EmadMokhtar Just released  [0.0.10 ](https://github.com/ekonstantinidis/django-rest-framework-docs/releases/tag/0.0.10) which includes this one!

**Comment by EmadMokhtar** [comment]
👍🏻 Nice, I'm so happy 😊😊😊

**Pull request merged**
